name: Run Unit Tests

on:
    push:
      branches: 
        - '*'         # matches every branch that doesn't contain a '/'
        - '*/*'       # matches every branch containing a single '/'
        - '**'        # matches every branch
    pull_request:
      branches:  "main"

jobs:
  build:
    if: ${{ github.event_name == 'push' || github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin' # See 'Supported distributions' for available options
        java-version: '11'

    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Install dependencies
      run: |
        cd server
        mvn install -DskipTests
    
    - name: Set up application-test.properties
      run: |
        cd src/main/resources
        echo "${{ secrets.APPLICATION_TEST }}" > application-test.properties

    - name: Run tests
      run: mvn test
